#!/usr/bin/env bash
#
# Generated by generate_linkfavs.py on 2025-03-25 18:55:25
# WARNING: This file is auto-generated. Manual changes may be overwritten.
#

set -e

IMAGE_ROOT="$HOME/Downloads/_aje_osx_desktop_backup"

IMAGES_TO_LINK=(
    "iMac Blue.heic"
    "iMac Green.heic"
    "iMac Orange.heic"
    "iMac Pink.heic"
    "iMac Purple.heic"
    "iMac Silver.heic"
    "iMac Yellow.heic"
)

. ./common.sh
main
