#!/usr/bin/env bash
#
# Generated by generate_linkfavs.py on 2025-03-25 19:00:44
# WARNING: This file is auto-generated. Manual changes may be overwritten.
#

set -e

IMAGE_ROOT="$HOME/Downloads/macOS Wallpapers"

IMAGES_TO_LINK=(
    "Big Sur Night Succulents.heic"
    "Big Sur Road.heic"
    "Big Sur Mountains.heic"
    "Big Sur Night Grasses.heic"
    "Big Sur Aerial.heic"
    "Big Sur Waters Edge.heic"
    "Big Sur Horizon.heic"
    "Big Sur Coastline.heic"
)

. ./common.sh
main
