#!/usr/bin/env bash
#
# Generated by generate_linkfavs.py on 2025-03-25 18:55:00
# WARNING: This file is auto-generated. Manual changes may be overwritten.
#

set -e

IMAGE_ROOT="$HOME/Downloads/_aje_osx_desktop_backup"

IMAGES_TO_LINK=(
    "Hello Metallic Blue.heic"
    "Hello Metallic Green.heic"
    "Hello Metallic Orange.heic"
    "Hello Metallic Pink.heic"
    "Hello Metallic Purple.heic"
    "Hello Metallic Silver.heic"
    "Hello Metallic Yellow.heic"
)

. ./common.sh
main
