#!/usr/bin/env bash
#
# Generated by generate_linkfavs.py on 2025-09-19 17:11:43
# WARNING: This file is auto-generated. Manual changes may be overwritten.
#

set -e

IMAGE_ROOT="$HOME/Downloads/macOS Wallpapers"

IMAGES_TO_LINK=(
    "Flow 2.jpg"
    "Flow 1.jpg"
    "Flow 3.jpg"
)

. ./common.sh
main
