#!/usr/bin/env bash
#
# Generated by generate_linkfavs.py on 2025-03-25 19:02:56
# WARNING: This file is auto-generated. Manual changes may be overwritten.
#

set -e

IMAGE_ROOT="$HOME/Downloads/macOS Wallpapers"

IMAGES_TO_LINK=(
    "Big Sur Night Grasses.heic"
    "Big Sur Night Succulents.heic"
)

. ./common.sh
main
